<?php
/**
 * STRENNA - List Active Strenna
 * Returns the active STRENNA entry
 */

// Start output buffering FIRST - before any includes
if (!ob_get_level()) {
    ob_start();
}

// Suppress error display (but log them)
ini_set('display_errors', '0');
error_reporting(E_ALL);

if (!defined('API_ACCESS')) {
    define('API_ACCESS', true);
}

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/security.php';
require_once __DIR__ . '/../config/constants.php';

// Clear any output that might have been generated by includes
if (ob_get_level()) {
    ob_clean();
}

// Set JSON header early
header('Content-Type: application/json');

try {
    $db = Database::getInstance()->getConnection();
    
    // Check if table exists
    // Check if table exists (suppress errors if it doesn't)
    try {
        $tableCheck = $db->query("SHOW TABLES LIKE 'strenna'");
        if ($tableCheck->rowCount() === 0) {
            // Table doesn't exist, return null
            if (ob_get_level()) {
                ob_clean();
            }
            echo json_encode([
                'success' => true,
                'data' => null
            ]);
            exit;
        }
    } catch (Exception $e) {
        // Table check failed, return null
        while (ob_get_level()) {
            ob_end_clean();
        }
        header('Content-Type: application/json');
        echo json_encode([
            'success' => true,
            'data' => null
        ]);
        exit;
    }
    
    $stmt = $db->prepare("
        SELECT id, year, title, content, image, is_active, created_at, updated_at
        FROM strenna
        WHERE is_active = 1
        ORDER BY year DESC, created_at DESC
        LIMIT 1
    ");
    
    $stmt->execute();
    $strenna = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if ($strenna) {
        // Format image URL
        if ($strenna['image']) {
            $image = $strenna['image'];
            if (strpos($image, 'uploads/') === 0 || strpos($image, '/uploads/') === 0) {
                $strenna['image'] = (strpos($image, '/') === 0 ? '' : '/') . $image;
            } elseif (!preg_match('/^https?:\/\//', $image) && strpos($image, '/') !== 0) {
                $strenna['image'] = '/uploads/images/' . $image;
            }
        }
        
        // Clean output buffer before JSON
        while (ob_get_level()) {
            ob_end_clean();
        }
        header('Content-Type: application/json');
        echo json_encode([
            'success' => true,
            'data' => $strenna
        ]);
        exit;
    } else {
        // Clean output buffer before JSON
        while (ob_get_level()) {
            ob_end_clean();
        }
        header('Content-Type: application/json');
        echo json_encode([
            'success' => true,
            'data' => null
        ]);
        exit;
    }
} catch (PDOException $e) {
    // Suppress any output before JSON
    while (ob_get_level()) {
        ob_end_clean();
    }
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'error' => 'Database error: ' . $e->getMessage()
    ]);
    exit;
} catch (Exception $e) {
    // Suppress any output before JSON
    while (ob_get_level()) {
        ob_end_clean();
    }
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'error' => 'Server error: ' . $e->getMessage()
    ]);
    exit;
}

