/**
 * Application Constants
 */

export const API_BASE_URL = '/api';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    CHECK: '/api/auth/check',
  },
  DASHBOARD: {
    STATS: '/api/dashboard/stats',
  },
  BIRTHDAY: {
    LIST: '/api/birthday/list',
    CREATE: '/api/birthday/create',
    UPDATE: '/api/birthday/update',
    DELETE: '/api/birthday/delete',
  },
  NEWS: {
    LIST: '/api/news/list',
    GET: '/api/news/get',
    CREATE: '/api/news/create',
    UPDATE: '/api/news/update',
    DELETE: '/api/news/delete',
  },
  MESSAGES: {
    LIST: '/api/messages/list',
    CREATE: '/api/messages/create',
    UPDATE: '/api/messages/update',
  },
  HOUSES: {
    LIST: '/api/houses/list',
    CREATE: '/api/houses/create',
    UPDATE: '/api/houses/update',
    DELETE: '/api/houses/delete',
  },
  BANNERS: {
    LIST: '/api/banners/list',
    CREATE: '/api/banners/create',
    UPDATE: '/api/banners/update',
    DELETE: '/api/banners/delete',
  },
  CIRCULARS: {
    LIST: '/api/circulars/list',
    ARCHIVE: '/api/circulars/archive',
    CREATE: '/api/circulars/create',
    UPDATE: '/api/circulars/update',
    DELETE: '/api/circulars/delete',
  },
  NEWSLINE: {
    LIST: '/api/newsline/list',
    CURRENT: '/api/newsline/current',
    ARCHIVE: '/api/newsline/archive',
    CREATE: '/api/newsline/create',
    UPDATE: '/api/newsline/update',
    DELETE: '/api/newsline/delete',
  },
  GALLERY: {
    LIST: '/api/gallery/list',
    CATEGORIES: '/api/gallery/categories',
    CREATE: '/api/gallery/create',
    UPDATE: '/api/gallery/update',
    DELETE: '/api/gallery/delete',
  },
  PROVINCIALS: {
    LIST: '/api/provincials/list',
    CURRENT: '/api/provincials/current',
    CREATE: '/api/provincials/create',
    UPDATE: '/api/provincials/update',
    DELETE: '/api/provincials/delete',
  },
  COUNCIL: {
    LIST: '/api/council/list',
    CREATE: '/api/council/create',
    UPDATE: '/api/council/update',
    DELETE: '/api/council/delete',
  },
  COMMISSIONS: {
    LIST: '/api/commissions/list',
    CREATE: '/api/commissions/create',
    UPDATE: '/api/commissions/update',
    DELETE: '/api/commissions/delete',
  },
  QUICK_LINKS: {
    LIST: '/api/quick-links/list',
    CREATE: '/api/quick-links/create',
    UPDATE: '/api/quick-links/update',
    DELETE: '/api/quick-links/delete',
  },
  COLLABORATIONS: {
    LIST: '/api/collaborations/list',
    CREATE: '/api/collaborations/create',
    UPDATE: '/api/collaborations/update',
    DELETE: '/api/collaborations/delete',
  },
  SETTINGS: {
    GET: '/api/settings/get',
    UPDATE: '/api/settings/update',
  },
  STRENNA: {
    LIST: '/api/strenna/list',
    GET: '/api/strenna/get',
    CREATE: '/api/strenna/create',
    UPDATE: '/api/strenna/update',
  },
  PAGES: {
    LIST: '/api/pages/list',
    GET: '/api/pages/get',
    CREATE: '/api/pages/create',
    UPDATE: '/api/pages/update',
    DELETE: '/api/pages/delete',
  },
  UPLOAD: {
    IMAGE: '/api/upload/image',
  },
} as const;

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  ABOUT_US: '/about-us',
  OUR_VISION: '/about-us/our-vision',
  OUR_MISSION: '/about-us/our-mission',
  DON_BOSCO: '/don-bosco',
  GC29: '/gc29',
  PROVINCIALS: '/provincials',
  VICE_PROVINCIAL: '/provincials/vice-provincial',
  ECONOMER: '/provincials/economer',
  PROVINCIAL_SECRETARY: '/provincials/provincial-secretary',
  COUNCIL: '/council',
  COUNCILLORS_2024_2025: '/council/councillors-2024-2025',
  DIMENSION: '/council/dimension',
  COMMISSIONS: '/council/commissions',
  COMMISSION_SCHOOL_EDUCATION: '/council/commissions/school-education',
  COMMISSION_HIGHER_EDUCATION: '/council/commissions/higher-education',
  COMMISSION_NON_FORMAL: '/council/commissions/non-formal',
  COMMISSION_YOUTH_AT_RISK: '/council/commissions/youth-at-risk',
  COMMISSION_MIGRANTS_DESK: '/council/commissions/migrants-desk',
  COMMISSION_YOUTH_CENTRE: '/council/commissions/youth-centre',
  COMMISSION_SCOUTS_GUIDE: '/council/commissions/scouts-guide',
  COMMISSION_HOSTEL_BOARDING: '/council/commissions/hostel-boarding',
  COMMISSION_SPORTS_ACADEMY: '/council/commissions/sports-academy',
  COMMISSION_FORMATION: '/council/commissions/formation',
  COMMISSION_SALESIAN_FAMILY: '/council/commissions/salesian-family',
  COMMISSION_COOPERATORS_ADMA: '/council/commissions/cooperators-adma',
  COMMISSION_PAST_PUPIL: '/council/commissions/past-pupil',
  COMMISSION_SOCIAL_COMMUNICATION: '/council/commissions/social-communication',
  COMMISSION_PROTECTOR_MINOR: '/council/commissions/protector-minor',
  COMMISSION_ECOLOGY: '/council/commissions/ecology',
  HOUSES: '/houses',
  DIOCESE_BONGAIGAON: '/houses/bongaigaon-diocese',
  DIOCESE_DIPHU: '/houses/diphu-diocese',
  DIOCESE_GUWAHATI: '/houses/guwahati-archdiocese',
  DIOCESE_NONGSTOIN: '/houses/nongstoin-diocese',
  DIOCESE_TEZPUR: '/houses/tezpur-diocese',
  DIOCESE_TURA: '/houses/tura-diocese',
  CIRCULARS: '/circulars',
  NEWSLINE: '/newsline',
  GALLERY: '/gallery',
  NEWS_DETAIL: '/news/:slug',
  ALL_NEWS: '/all-news',
  PROVINCE: '/province',
  PROVINCIAL_MESSAGE: '/provincial-message',
  ADMIN: {
    DASHBOARD: '/admin',
    BIRTHDAY: '/admin/birthday',
    NEWS: '/admin/news',
    MESSAGES: '/admin/messages',
    HOUSES: '/admin/houses',
    BANNERS: '/admin/banners',
    HERO_SLIDER: '/admin/hero-slider',
    CIRCULARS: '/admin/circulars',
    NEWSLINE: '/admin/newsline',
    GALLERY: '/admin/gallery',
    PROVINCIALS: '/admin/provincials',
    COUNCIL: '/admin/council',
    COMMISSIONS: '/admin/commissions',
    QUICK_LINKS: '/admin/quick-links',
    COLLABORATIONS: '/admin/collaborations',
    SETTINGS: '/admin/settings',
    STRENNA: '/admin/strenna',
    PAGES: '/admin/pages',
  },
} as const;

